import Foundation

/// The compose project this app owns: one Postgres, one relay, two volumes, and
/// a tunnel when the operator has asked for a public front door.
///
/// It is written from here rather than shipped as a file so the port, the image
/// tag and the front door in the running stack always match what the panel is
/// showing.
enum Compose {
    static let project = "weald-relay-host"
    static let image = "ghcr.io/weald-protocol/wealdrelay"

    /// Everything the panel decides, in one value, so adding a knob does not add
    /// a positional argument to a call three files away.
    struct Plan {
        var port: Int
        var tag: String
        var retentionDays: Int
        var maxStorageGB: Int
        var tunnel: Tunnel.Mode = .off
        /// What the outside world calls this relay. Only a named tunnel knows it
        /// up front; a quick tunnel is told its hostname by the edge after it
        /// connects, and the panel rewrites links once it hears back.
        var hostname: String = "localhost"
        var tunnelToken: String = ""
    }

    /// Where the compose file, the tunnel environment and the blob volume live.
    static var supportDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent("WealdRelayHost", isDirectory: true)
    }

    static var file: URL { supportDirectory.appendingPathComponent("compose.yml") }

    /// Compose reads `.env` from the project directory on its own, which is how
    /// the tunnel token reaches the container without being written into the
    /// compose file the operator is invited to read.
    static var environmentFile: URL { supportDirectory.appendingPathComponent(".env") }

    static func write(_ plan: Plan) throws {
        try FileManager.default.createDirectory(
            at: supportDirectory, withIntermediateDirectories: true
        )
        try yaml(plan).data(using: .utf8)!.write(to: file, options: .atomic)
        try writeEnvironment(plan)
    }

    /// The token is the one secret in the stack, so the file holding it is
    /// rewritten every start, emptied when the tunnel is off, and owner-readable
    /// only.
    private static func writeEnvironment(_ plan: Plan) throws {
        let body = plan.tunnel == .named && !plan.tunnelToken.isEmpty
            ? "WEALD_TUNNEL_TOKEN=\(plan.tunnelToken)\n"
            : "WEALD_TUNNEL_TOKEN=\n"
        try body.data(using: .utf8)!.write(to: environmentFile, options: .atomic)
        try? FileManager.default.setAttributes(
            [.posixPermissions: 0o600], ofItemAtPath: environmentFile.path
        )
    }

    /// `self_host` is the relay's default profile, so it is not set here: the
    /// posture variable is left to the binary rather than restated in a file a
    /// user might edit.
    static func yaml(_ plan: Plan) -> String {
        """
        # Generated by Weald Relay Host. Edits are overwritten on the next start.
        name: \(project)

        services:
          db:
            image: postgres:16-alpine
            restart: unless-stopped
            environment:
              POSTGRES_USER: weald
              POSTGRES_PASSWORD: weald
              POSTGRES_DB: weald_relay
            volumes:
              - db:/var/lib/postgresql/data
            healthcheck:
              test: ["CMD-SHELL", "pg_isready -U weald -d weald_relay"]
              interval: 2s
              timeout: 3s
              retries: 30

          # The relay image is distroless and runs as uid 65532 with no shell, so
          # it cannot take ownership of a fresh named volume itself. One
          # short-lived container does it and exits.
          blobs-init:
            image: alpine:3.20
            command: ["sh", "-c", "mkdir -p /var/lib/weald/blobs && chown -R 65532:65532 /var/lib/weald"]
            volumes:
              - blobs:/var/lib/weald

          relay:
            image: \(image):\(plan.tag)
            restart: unless-stopped
            depends_on:
              db:
                condition: service_healthy
              blobs-init:
                condition: service_completed_successfully
            ports:
              - "\(plan.port):\(plan.port)"
            environment:
              WEALD_RELAY_DATABASE_URL: postgres://weald:weald@db:5432/weald_relay
              WEALD_RELAY_STORAGE_URL: file:///var/lib/weald/blobs
              WEALD_RELAY_LISTEN: 0.0.0.0:\(plan.port)
              WEALD_RELAY_HOSTNAME: \(plan.hostname)
              WEALD_RELAY_TLS: "off"
              WEALD_RELAY_RETENTION_DAYS: "\(plan.retentionDays)"
              WEALD_RELAY_MAX_STORAGE_GB: "\(plan.maxStorageGB)"
            volumes:
              - blobs:/var/lib/weald
        \(tunnel(plan))
        volumes:
          db:
          blobs:
        """
    }

    /// The front door, when there is one.
    ///
    /// `WEALD_RELAY_TLS` stays `off` in both tunnel modes on purpose: the edge
    /// terminates TLS and forwards plaintext over a connection this stack never
    /// exposes, which is the documented proxy posture and not a downgrade. The
    /// relay's port is still published to the Mac, so the loopback URL and the
    /// health check keep working while the tunnel is up.
    private static func tunnel(_ plan: Plan) -> String {
        switch plan.tunnel {
        case .off:
            return ""
        case .quick:
            return service(
                command: #"["tunnel", "--no-autoupdate", "--url", "http://relay:\#(plan.port)"]"#,
                note: """
                  # A quick tunnel. Cloudflare mints a throwaway hostname at
                  # connect time and prints it to this container's log, which is
                  # where the panel reads it from.
                """
            )
        case .named:
            return service(
                command: #"["tunnel", "--no-autoupdate", "run", "--token", "${WEALD_TUNNEL_TOKEN}"]"#,
                note: """
                  # A tunnel from the operator's own Cloudflare account. Its
                  # hostname and its ingress rule live there; point the ingress at
                  # http://relay:\(plan.port). The token comes from .env beside
                  # this file and is held in the login keychain.
                """
            )
        }
    }

    private static func service(command: String, note: String) -> String {
        """

        \(note)
          tunnel:
            image: \(Tunnel.image)
            restart: unless-stopped
            depends_on:
              - relay
            command: \(command)

        """
    }
}
