import Foundation

/// The compose project this app owns: one Postgres, one relay, two volumes.
///
/// It is written from here rather than shipped as a file so the port and the
/// image tag in the running stack always match what the panel is showing.
enum Compose {
    static let project = "weald-relay-host"
    static let image = "ghcr.io/weald-protocol/wealdrelay"

    /// Where the compose file, the operator token and the blob volume live.
    static var supportDirectory: URL {
        let base = FileManager.default.urls(for: .applicationSupportDirectory, in: .userDomainMask)[0]
        return base.appendingPathComponent("WealdRelayHost", isDirectory: true)
    }

    static var file: URL { supportDirectory.appendingPathComponent("compose.yml") }

    static func write(port: Int, tag: String, retentionDays: Int, maxStorageGB: Int) throws {
        try FileManager.default.createDirectory(
            at: supportDirectory, withIntermediateDirectories: true
        )
        try yaml(port: port, tag: tag, retentionDays: retentionDays, maxStorageGB: maxStorageGB)
            .data(using: .utf8)!
            .write(to: file, options: .atomic)
    }

    /// `self_host` is the relay's default profile, so it is not set here: the
    /// posture variable is left to the binary rather than restated in a file a
    /// user might edit.
    static func yaml(port: Int, tag: String, retentionDays: Int, maxStorageGB: Int) -> String {
        """
        # Generated by Weald Relay Host. Edits are overwritten on the next start.
        name: \(project)

        services:
          db:
            image: postgres:16-alpine
            restart: unless-stopped
            environment:
              POSTGRES_USER: weald
              POSTGRES_PASSWORD: weald
              POSTGRES_DB: weald_relay
            volumes:
              - db:/var/lib/postgresql/data
            healthcheck:
              test: ["CMD-SHELL", "pg_isready -U weald -d weald_relay"]
              interval: 2s
              timeout: 3s
              retries: 30

          # The relay image is distroless and runs as uid 65532 with no shell, so
          # it cannot take ownership of a fresh named volume itself. One
          # short-lived container does it and exits.
          blobs-init:
            image: alpine:3.20
            command: ["sh", "-c", "mkdir -p /var/lib/weald/blobs && chown -R 65532:65532 /var/lib/weald"]
            volumes:
              - blobs:/var/lib/weald

          relay:
            image: \(image):\(tag)
            restart: unless-stopped
            depends_on:
              db:
                condition: service_healthy
              blobs-init:
                condition: service_completed_successfully
            ports:
              - "\(port):\(port)"
            environment:
              WEALD_RELAY_DATABASE_URL: postgres://weald:weald@db:5432/weald_relay
              WEALD_RELAY_STORAGE_URL: file:///var/lib/weald/blobs
              WEALD_RELAY_LISTEN: 0.0.0.0:\(port)
              WEALD_RELAY_HOSTNAME: localhost
              WEALD_RELAY_TLS: "off"
              WEALD_RELAY_RETENTION_DAYS: "\(retentionDays)"
              WEALD_RELAY_MAX_STORAGE_GB: "\(maxStorageGB)"
            volumes:
              - blobs:/var/lib/weald

        volumes:
          db:
          blobs:
        """
    }
}
